spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root       # 👈 replace with your MySQL username
    password: root       # 👈 replace with your MySQL password

  jpa:
    hibernate:
      ddl-auto: none   # options: create | create-drop | update | validate | none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
